# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrXaO3yZDUESYonXYclL-u1RJVjdBwHB
"""

# ==============================================================================
# PROYEK: PEMETAAN DAN CLUSTERING PENYEBARAN HIV/AIDS JAWA BARAT
# DATA: Dinas Kesehatan (Open Data Jabar)
# METODE: K-Means Clustering & Geospatial Mapping
# ==============================================================================

import pandas as pd
import json
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ------------------------------------------------------------------------------
# BAGIAN 1: PRE-PROCESSING DATA (PERSIAPAN)
# ------------------------------------------------------------------------------
print("⚙️ [1/5] Memuat dan Membersihkan Data...")

# 1. Load Data CSV
csv_filename = 'jumlah_kasus_hiv_berdasarkan_kelompok_umur_v1_data.csv'
try:
    df = pd.read_csv(csv_filename)
except FileNotFoundError:
    print("❌ Error: File CSV tidak ditemukan. Upload dulu file CSV Anda.")

# 2. Load GeoJSON (Peta Batas Kab/Kota)
geojson_filename = '/content/jawa_barat_32_batas_kabkota.geojson'
try:
    with open(geojson_filename, 'r') as f:
        jabar_geojson = json.load(f)
except FileNotFoundError:
    print("❌ Error: File GeoJSON tidak ditemukan. Upload dulu file GeoJSON Anda.")

# 3. Transformasi Data (Pivot Table)
# Kita butuh satu baris per Kota, dengan kolom-kolom adalah Kelompok Umur
df_agg = df.groupby(['nama_kabupaten_kota', 'kelompok_umur'])['jumlah_kasus'].sum().reset_index()
df_pivot = df_agg.pivot(index='nama_kabupaten_kota', columns='kelompok_umur', values='jumlah_kasus').fillna(0).reset_index()

# 4. Hitung Total Kasus
df_total = df.groupby('nama_kabupaten_kota')['jumlah_kasus'].sum().reset_index()
df_total.columns = ['nama_kabupaten_kota', 'Total_Kasus']

# 5. Gabungkan Data
df_final = pd.merge(df_total, df_pivot, on='nama_kabupaten_kota')

# 6. Normalisasi Nama (PENTING: Agar CSV cocok dengan GeoJSON)
# GeoJSON menggunakan Title Case (Contoh: "Kabupaten Bandung"), CSV menggunakan Uppercase.
def normalisasi_nama(nama):
    return nama.title() # Ubah "KOTA BANDUNG" jadi "Kota Bandung"

df_final['nama_peta'] = df_final['nama_kabupaten_kota'].apply(normalisasi_nama)
print("✅ Data siap. Jumlah Wilayah:", len(df_final))


# ------------------------------------------------------------------------------
# BAGIAN 2: METODOLOGI (VALIDASI CLUSTER) -> UNTUK BAB 3 METODOLOGI
# ------------------------------------------------------------------------------
print("\n⚙️ [2/5] Menjalankan Algoritma K-Means & Validasi Elbow...")

# Fitur untuk clustering (Kolom Umur)
features = df_final.columns[2:8] # Mengambil kolom umur 0-4 s/d 50+
X = df_final[features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Grafik Elbow
inertia = []
range_k = range(1, 10)
for k in range_k:
    kmeans_temp = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans_temp.fit(X_scaled)
    inertia.append(kmeans_temp.inertia_)

fig_elbow = go.Figure(data=go.Scatter(x=list(range_k), y=inertia, mode='lines+markers'))
fig_elbow.update_layout(
    title='<b>Uji Validasi Elbow Method</b><br>(Dasar Penentuan k=3 Cluster)',
    xaxis_title='Jumlah Cluster (k)',
    yaxis_title='Inertia (Sum of Squared Errors)',
    template='plotly_white',
    height=450
)
fig_elbow.show()


# ------------------------------------------------------------------------------
# BAGIAN 3: PROSES CLUSTERING & LABELING
# ------------------------------------------------------------------------------
# Eksekusi K-Means dengan k=3
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)
df_final['Cluster'] = clusters

# Mapping Label (Agar Cluster 0,1,2 punya arti Rendah/Sedang/Tinggi)
cluster_mean = df_final.groupby('Cluster')['Total_Kasus'].mean().sort_values()
risk_map = {
    cluster_mean.index[0]: 'Resiko Rendah',
    cluster_mean.index[1]: 'Resiko Sedang',
    cluster_mean.index[2]: 'Resiko Tinggi (Hotspot)'
}
df_final['Kategori_Resiko'] = df_final['Cluster'].map(risk_map)


# ------------------------------------------------------------------------------
# BAGIAN 4: HASIL VISUALISASI PETA -> UNTUK BAB 4 HASIL & PEMBAHASAN
# ------------------------------------------------------------------------------
print("\n⚙️ [3/5] Membuat Peta Choropleth (Heatmap Wilayah)...")

color_map = {'Resiko Tinggi (Hotspot)': 'red', 'Resiko Sedang': 'orange', 'Resiko Rendah': 'green'}

fig_map = px.choropleth_mapbox(
    df_final,
    geojson=jabar_geojson,
    locations='nama_peta',        # Nama di CSV
    featureidkey="properties.name", # Nama di GeoJSON
    color='Kategori_Resiko',
    color_discrete_map=color_map,
    hover_name='nama_kabupaten_kota',
    hover_data={'Total_Kasus': True, '15-19': True, '20-24': True, 'nama_peta': False, 'Kategori_Resiko': False},
    center={"lat": -6.9175, "lon": 107.6191},
    zoom=7.3,
    mapbox_style="carto-positron",
    title="<b>PETA ZONASI RISIKO PENYEBARAN HIV/AIDS JAWA BARAT</b><br><i>(Visualisasi Sebaran Wilayah Berdasarkan Clustering)</i>"
)
fig_map.update_layout(margin={"r":0,"t":40,"l":0,"b":0}, legend_title_text='Status Wilayah')
fig_map.show()


# ------------------------------------------------------------------------------
# BAGIAN 5: ANALISIS STATISTIK MENDALAM -> UNTUK BAB 4 PEMBAHASAN
# ------------------------------------------------------------------------------
print("\n⚙️ [4/5] Membuat Grafik Analisis Karakteristik & Remaja...")

# A. Grafik Profil Cluster (Pola Umur)
cluster_profile = df_final.groupby('Kategori_Resiko')[features].mean().reset_index()
cluster_melt = cluster_profile.melt(id_vars='Kategori_Resiko', var_name='Kelompok Umur', value_name='Rata-rata Kasus')

fig_profile = px.bar(
    cluster_melt, x='Kelompok Umur', y='Rata-rata Kasus', color='Kategori_Resiko',
    barmode='group',
    color_discrete_map=color_map,
    category_orders={'Kategori_Resiko': ['Resiko Rendah', 'Resiko Sedang', 'Resiko Tinggi (Hotspot)']},
    title='<b>Analisis Karakteristik Cluster Berdasarkan Umur</b><br>(Bukti Kerentanan pada Usia Produktif 25-49 Thn)',
    labels={'Rata-rata Kasus': 'Rata-rata Kasus per Kota'}
)
fig_profile.show()

# B. Grafik Top 10 Kasus Remaja (15-19 Tahun)
top_remaja = df_final.sort_values(by='15-19', ascending=False).head(10)

fig_remaja = px.bar(
    top_remaja, x='15-19', y='nama_kabupaten_kota', orientation='h',
    color='Kategori_Resiko', color_discrete_map=color_map,
    text='15-19',
    title='<b>10 Wilayah dengan Kasus Remaja (15-19 Thn) Tertinggi</b><br>(Dasar Rekomendasi Program Sekolah/Edukasi)',
    labels={'15-19': 'Jumlah Kasus Remaja'}
)
fig_remaja.update_layout(yaxis={'categoryorder':'total ascending'})
fig_remaja.show()


# ------------------------------------------------------------------------------
# BAGIAN 6: TEXT REPORT -> UNTUK BAB 5 KESIMPULAN & SARAN
# ------------------------------------------------------------------------------
print("\n" + "="*80)
print(" DRAFT OTOMATIS: REKOMENDASI & KESIMPULAN")
print("="*80)

# Cari data ekstrem
hotspots = df_final[df_final['Kategori_Resiko'] == 'Resiko Tinggi (Hotspot)']
avg_hotspot = cluster_profile[cluster_profile['Kategori_Resiko']=='Resiko Tinggi (Hotspot)']['25-49'].values[0]
kota_max_remaja = top_remaja.iloc[0]['nama_kabupaten_kota']

print(f"1. KESIMPULAN WILAYAH:")
print(f"   Berdasarkan hasil clustering, teridentifikasi {len(hotspots)} wilayah 'HOTSPOT' (Zona Merah).")
print(f"   Daftar Wilayah: {', '.join(hotspots['nama_kabupaten_kota'].tolist())}.")
print(f"   Wilayah ini memerlukan alokasi sumber daya kesehatan terbesar.")

print(f"\n2. TEMUAN KHUSUS (REMAJA & PRODUKTIF):")
print(f"   - Usia Produktif (25-49 thn) menjadi penyumbang kasus terbesar di zona merah (Rata-rata {avg_hotspot:.0f} kasus/kota).")
print(f"   - {kota_max_remaja} menjadi wilayah dengan kerentanan tertinggi pada usia remaja (15-19 tahun).")

print(f"\n3. SARAN KEBIJAKAN:")
print(f"   - Untuk {kota_max_remaja} dan sekitarnya: Wajibkan skrining kesehatan berkala di SMA/SMK.")
print(f"   - Untuk Zona Hotspot: Fokuskan Mobile VCT (Tes HIV Keliling) di kawasan industri/pabrik.")
print("="*80)

# ==============================================================================
# ANALISIS TREN KENAIKAN KASUS PER TAHUN (TIME SERIES)
# ==============================================================================

import pandas as pd
import plotly.express as px
import json

# 1. Load Data Ulang (Agar variabel bersih)
csv_filename = '/content/jumlah_kasus_hiv_berdasarkan_kelompok_umur_v1_data.csv'
geojso_filename = '/content/jawa_barat_32_batas_kabkota.geojson'

df = pd.read_csv(csv_filename)
with open(geojson_filename, 'r') as f:
    jabar_geojson = json.load(f)

# ------------------------------------------------------------------------------
# VISUALISASI 1: TREN TOTAL KASUS JAWA BARAT (Line Chart)
# ------------------------------------------------------------------------------
# Agregasi data per tahun
df_trend_jabar = df.groupby('tahun')['jumlah_kasus'].sum().reset_index()

fig_line = px.line(
    df_trend_jabar,
    x='tahun',
    y='jumlah_kasus',
    markers=True,
    title='<b>Tren Total Kasus HIV/AIDS Jawa Barat (Perkembangan Tahunan)</b>',
    labels={'jumlah_kasus': 'Total Kasus', 'tahun': 'Tahun'}
)
fig_line.update_traces(line_color='red', line_width=4)
fig_line.show()


# ------------------------------------------------------------------------------
# VISUALISASI 2: PERBANDINGAN TREN 5 KOTA DENGAN KASUS TERTINGGI
# ------------------------------------------------------------------------------
# Mencari 5 kota dengan total kasus terbanyak sepanjang sejarah
top_5_cities = df.groupby('nama_kabupaten_kota')['jumlah_kasus'].sum().nlargest(5).index.tolist()

# Filter data hanya untuk 5 kota tersebut
df_top_5 = df[df['nama_kabupaten_kota'].isin(top_5_cities)]
df_trend_kota = df_top_5.groupby(['nama_kabupaten_kota', 'tahun'])['jumlah_kasus'].sum().reset_index()

fig_multiline = px.line(
    df_trend_kota,
    x='tahun',
    y='jumlah_kasus',
    color='nama_kabupaten_kota',
    markers=True,
    title='<b>Dinamika Kasus di 5 Wilayah "Hotspot" Utama</b>',
    labels={'nama_kabupaten_kota': 'Wilayah'}
)
fig_multiline.show()


# ------------------------------------------------------------------------------
# VISUALISASI 3: PETA ANIMASI (TIMELINE MAP)
# ------------------------------------------------------------------------------
# Persiapan Data untuk Peta Animasi
df_map_yearly = df.groupby(['nama_kabupaten_kota', 'tahun'])['jumlah_kasus'].sum().reset_index()

# Normalisasi Nama agar Cocok dengan GeoJSON (Wajib)
def normalisasi_nama(nama):
    return nama.title()

df_map_yearly['nama_peta'] = df_map_yearly['nama_kabupaten_kota'].apply(normalisasi_nama)

# Pastikan data urut berdasarkan tahun agar animasi jalan mulus
df_map_yearly = df_map_yearly.sort_values('tahun')

fig_anim = px.choropleth_mapbox(
    df_map_yearly,
    geojson=jabar_geojson,
    locations='nama_peta',
    featureidkey="properties.name",
    color='jumlah_kasus',
    animation_frame='tahun', # INI KUNCINYA: Membuat Slider Tahun

    # Skala Warna (Tetap agar perubahan terlihat jelas)
    range_color=[0, df_map_yearly['jumlah_kasus'].max()],
    color_continuous_scale="Reds",

    hover_name='nama_kabupaten_kota',
    center={"lat": -6.9175, "lon": 107.6191},
    zoom=7,
    mapbox_style="carto-positron",
    title="<b>Peta Sebaran Kasus HIV per Tahun (Tekan Tombol Play ▶️)</b>"
)
fig_anim.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
fig_anim.show()
